# Generated by Django 5.1 on 2024-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='F', max_length=10)),
                ('registration', models.CharField(default='000000', max_length=15, unique=True)),
                ('date_birth', models.DateField(default='2000-01-01')),
                ('level', models.CharField(default='Non spécifiée', max_length=50)),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('city', models.CharField(default='Inconnue', max_length=50)),
            ],
        ),
    ]
